name: Publish Package (NPM) and Deploy DS (Design System)

on: 
  workflow_run:
    workflows: ["Test"]
    branches: 
      - main
    types: 
      - completed

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    name: Publish
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build:lib
      
      - name: Deploy if the version has changed
        uses: JS-DevTools/npm-publish@v3
        id: publish
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
      
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    name: Deploy
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build:storybook
      
      - name: Deploy to S3 bucket
        run: aws s3 sync ./storybook-static/ s3://opire-design-system --delete